In [ ]:
import pandas as pd
import numpy as np

df_vendas=pd.read_csv("vendas_tech.csv", encoding="utf-8", sep=',', low_memory=False) ##sep=SEPARADOR
df_gerentes=pd.read_excel("gerentes_lojas.xlsx")

In [ ]:
##INSPEÇÃO
#display(df_vendas.head(15)) ##PRIMEIRAS
#display(df_vendas.tail(15)) ##ULTIMAS
#display(df_vendas.sample(15)) ##AMOSTRA/LINHAS ALEATÓRIAS
#display(df_vendas.shape)  ##(LINHAS, COLUNAS)
#display(df_vendas.columns) ##[COLUNAS]
df_vendas.info() ##INFORMAÇÕES
display(df_vendas.describe()) ##DESCRIÇÃO

In [48]:
##TRATAMENTO DE ERROS
#colunas
""" display(list(df_vendas.columns))
display(df_vendas["Loja"])  ##SÉRIE
display(df_vendas[["Loja", "Produto"]]) ##SOMENTE AS COLUNAS SELECIONADAS """

df_analise=df_vendas.drop(columns=["Data_Base"], errors='ignore')
display(df_analise.columns)

#nulos
#df_analise=df_vendas.dropna()  ##EXCLUI TODAS AS LINHAS COM VALORES NULOS (1 ou mais)
df_analise["Loja"]=df_analise["Loja"].fillna("Online")

#tipos de dados
df_analise["Data"]=pd.to_datetime(df_vendas["Data"], format=r'%Y-%m-%d')

#padronização
df_analise["Loja"]=df_analise["Loja"].str.strip()
df_analise["Loja"]=df_analise["Loja"].str.title()

#duplicatas
df_analise=df_analise.drop_duplicates(subset=["ID_Pedido", "Loja", "Produto"], keep='first') #subset->colunas avaliados / Keep->Manter

display(df_analise)
df_analise.info()

Index(['ID_Pedido', 'Data', 'Loja', 'Produto', 'Preco_Unitario', 'Qtd',
       'Cliente'],
      dtype='object')

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100000 non-null  int64
 1   Data            100000 non-null  datetime64[ns]
 2   Loja            100000 non-null  object
 3   Produto         100000 non-null  object
 4   Preco_Unitario  100000 non-null  float64
 5   Qtd             100000 non-null  int64
 6   Cliente         100000 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 6.1+ MB

In [ ]:
##CRIANDO NOVAS COLUNAS:

#FATURAMENTO
df_analise["Faturamento"]=df_analise["Preco_Unitario"]*df_analise["Qtd"]

#FORMA DA VENDA
#np.where(condição, se for True, se for False)
df_analise["Forma_Venda"]=np.where(df_analise["Loja"]=="Online", "Online", "Presencial")

#REGIÃO
#display(df_analise["Loja"].unique()) ##MOSTRA OS VALORES únicos DENTRO DE UMA COLUNA
regioes={
    'São Paulo':'Sudeste',
    'Belo Horizonte': 'Sudeste', 
    'Online': 'Online', 
    'Rio De Janeiro': 'Sudeste',
    'Salvador': 'Nordeste', 
    'Recife': 'Nordeste', 
    'Curitiba': 'Sul', 
    'Porto Alegre': 'Sul'
}
df_analise["Região"]=df_analise["Loja"].map(regioes)  ##Para algo mais complexo, usar uma função no .map()

display(df_analise.head(10))

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_Venda,Região
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial,Sudeste
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Presencial,Sudeste
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0,Online,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Sudeste
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Presencial,Sudeste
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809,40.0,Presencial,Sudeste
6,7,2024-12-08,Salvador,"Monitor 27""",1200.0,1,Cliente_11076,1200.0,Presencial,Nordeste
7,8,2024-09-12,São Paulo,"Monitor 27""",1200.0,2,Cliente_14053,2400.0,Presencial,Sudeste
8,9,2023-05-20,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_19175,120.0,Presencial,Sudeste
9,10,2024-10-16,Recife,Notebook HP,3200.0,1,Cliente_13508,3200.0,Presencial,Nordeste

In [59]:
##ANALISAR
display(df_analise.isna().sum())

ID_Pedido         0
Data              0
Loja              0
Produto           0
Preco_Unitario    0
Qtd               0
Cliente           0
Faturamento       0
Forma_Venda       0
Região            0
dtype: int64